project:
  type: website
  render:
    - index.qmd
    - lessons/
  resources:
    - CNAME
    - robots.txt
    - resources/
  preview:
    port: 7827
    browser: false
    navigate: false
    timeout: 3600

website:
  title: Adventures in Computer Science
  description: Development
  # site-url: https://slides.example.com/
  # image: /images/01.png
  favicon: /images/favicon.svg
  page-footer: Alan Schoenecke, 2026
  page-navigation: true
  open-graph: true
  search: true
  navbar:
    foreground: black
    background: "#f87C63"

format:
  html:
    canonical-url: true
    license: CC BY-NC-SA
    toc: true
    toc-expand: 2
    code-fold: true
    smooth-scroll: true
    page-layout: full
    fig-align: center
    respect-user-color-scheme: true
    theme:
      light:
        - sandstone
#        - styles.scss
      dark:
        - darkly
    mermaid:
      theme: neutral
    grid:
      body-width: 1800px
  revealjs:
    author: Al Schoenecke
    center: true
    date-format: full
    transition: fade
    default-timing: 60
    preview-links: false
    link-external-newwindow: true
    link-external-icon: true
    pause: false
    code-block-height: 800px
    code-annotations: select
    tbl-cap-location: bottom
    slide-number: true
    pdf-separate-fragments: false
    theme: serif
    css: '/slides.css'
    mermaid:
      theme: default
    mermaid-format: png
    width: 1600
    height: 900
    chalkboard: false
    hash-type: number
    multiplex: false
